---
- name: Basic CentOS | Install utils
  package:
    pkg:
      - vim
      - fail2ban
      - ntp
      - logrotate
      - yum-cron
      - yum-utils
      - iptables-services
      - policycoreutils-python
      - rsyslog
      - openssh-server
      - python3
    state: present
    update_cache: true

- name: Basic CentOS | Shell Alias
  copy:
    src: alias.sh
    dest: /etc/profile.d/alias.sh
    mode: 0555
  when: alias

- name: Basic CentOS | Configure yumcron
  import_tasks: yumcron.yml
  when: yumcron
  tags: yumcron

- name: Basic CentOS | Configure passwords
  import_tasks: passwords.yml
  when: passwords
  tags: passwords

- name: Basic CentOS | Disable zeroconf
  lineinfile:
    dest: "/etc/sysconfig/network"
    regexp: ^NOZEROCONF=
    line: NOZEROCONF=yes
    state: present
    mode: 0555
    create: true

- name: Basic CentOS | harden rsyslog conf
  file:
    path: /etc/rsyslog.conf
    mode: "{{ rsyslog_mask }}"
  when: hardenrsyslog

- name: Basic CentOS | harden rsyslog d
  file:
    path: /etc/rsyslog.d
    recurse: true
    mode: "{{ rsyslog_mask }}"
  when: hardenrsyslog

- name: Basic CentOS | Configure sshd
  import_tasks: sshd.yml
  when: sshd
  tags: ssh

- name: Basic CentOS |upgrade any out of date packages
  yum:
    name: '*'
    state: latest
    update_cache: true
  when: updateall
  tags:
    - skip_ansible_lint
    - update


- name: Basic CentOS | Reboot check
  import_tasks: reboot.yml
  when: allow_reboot
  tags: reboot

- name: Basic CentOS | SMB Check
  import_tasks: smb.yml
  when: secure_smb
  tags: smb
