---
- name: Basic CentOS | Install dnf
  ansible.builtin.package:
    name: "dnf"
  vars:
    ansible_python_interpreter: "/usr/bin/python2"
  when:
    - "ansible_distribution == 'CentOS'"
    - "ansible_distribution_major_version | int == 7"

- name: Basic CentOS | Install utils
  ansible.builtin.dnf:
    name: "{{ default_packages }}"
    state: present
    update_cache: true
  vars:
    ansible_python_interpreter: "/usr/bin/python2"
  when:
    - "ansible_distribution == 'CentOS'"
    - "ansible_distribution_major_version | int == 7"

- name: Basic CentOS | Install utils
  ansible.builtin.dnf:
    name: "{{ default_packages }}"
    state: present
    update_cache: true
  when:
    - "ansible_distribution == 'CentOS'"
    - "ansible_distribution_major_version | int == 8"

- name: Basic CentOS | Shell Alias
  ansible.builtin.copy:
    src: alias.sh
    dest: /etc/profile.d/alias.sh
    mode: 0555
  when: alias

- name: Basic CentOS | Configure yumcron
  ansible.builtin.import_tasks: yumcron.yml
  when: customyumcron
  tags: customyumcron

- name: Basic CentOS | Configure passwords
  ansible.builtin.import_tasks: passwords.yml
  when: passwords
  tags: passwords

- name: Basic CentOS | Disable zeroconf
  ansible.builtin.lineinfile:
    dest: "/etc/sysconfig/network"
    regexp: ^NOZEROCONF=
    line: NOZEROCONF=yes
    state: present
    mode: 0555
    create: true

- name: Basic CentOS | Configure sshd
  ansible.builtin.import_tasks: sshd.yml
  when: sshd
  tags: ssh

- name: Basic CentOS | upgrade any out of date packages
  ansible.builtin.yum:
    name: '*'
    state: latest
    update_cache: true
  vars:
    ansible_python_interpreter: "/usr/bin/python2"
  when:
    - "ansible_distribution == 'CentOS'"
    - "ansible_distribution_major_version | int == 7"
    - updateall
  tags:
    - skip_ansible_lint
    - update

- name: Basic CentOS | upgrade any out of date packages
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: true
  when:
    - "ansible_distribution == 'CentOS'"
    - "ansible_distribution_major_version | int == 8"
    - updateall
  tags:
    - skip_ansible_lint
    - update

- name: Basic CentOS | Reboot check
  ansible.builtin.import_tasks: reboot.yml
  when: allow_reboot
  tags: reboot

- name: Basic CentOS | SMB Check
  ansible.builtin.import_tasks: smb.yml
  when: secure_smb
  tags: smb
