---
- name: Basic CentOS | check reboot
  ansible.builtin.shell: needs-restarting -r
  register: rebootcheck_out
  ignore_errors: true
  changed_when: false
  tags:
    - skip_ansible_lint

- name: Basic CentOS | Reboot
  ansible.builtin.reboot:
    reboot_timeout: 3600
    # if the exit is not 0 then we need to reboot
  when: rebootcheck_out.rc != 0

- name: Basic CentOS | Nightly reboot
  ansible.builtin.cron:
    name: "Update Reboot check"
    minute: "13"
    hour: "0"
    job: "needs-restarting -r || shutdown -rt now"
  when: schedule_update_reboot
