---
- name: Basic CentOS | Cron Update
  ansible.builtin.copy:
    src: update.py
    dest: /usr/local/bin/yumupdate.py
    mode: 0550
    owner: root
    group: root

- name: Basic CentOS | Update Daily
  ansible.builtin.cron:
    name: "Cron Updates"
    minute: "0"
    hour: "2"
    job: "/usr/local/bin/yumupdate.py"